name: pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
      # with:
        # token: ${{ secrets.PAT_TOKEN }}
    - uses: actions/setup-node@v4
    - run: npm i && npm run build
    - uses: actions/configure-pages@v4
    - uses: actions/upload-pages-artifact@v3
      with:
        path: 'example/encoded'
    - uses: actions/deploy-pages@v4
      id: deployment
